#!/usr/bin/env python3
"""Extract the IQ2_XXS lookup tables (iq2xxs_grid, ksigns_iq2xs) from
cuda/mmq/ggml-common.h and emit them as HLSL constants (for the Vulkan MoE
kernels) and as C host tables (for the smoke-test reference).

Outputs:
  vulkan/shaders/iq2_tables.hlsl
  vulkan/shaders/iq2_tables_host.h
"""

import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
SRC = os.path.normpath(os.path.join(REPO, "cuda", "mmq", "ggml-common.h"))
HLSL_OUT = os.path.join(REPO, "vulkan", "shaders", "iq2_tables.hlsl")
HOST_OUT = os.path.join(REPO, "vulkan", "shaders", "iq2_tables_host.h")

BEGIN_RE = re.compile(r"GGML_TABLE_BEGIN\(([^,]+),\s*([A-Za-z0-9_]+),\s*(\d+)\)")
HEX_RE = re.compile(r"(?:0x[0-9a-fA-F]+|\d+)")


def parse_tables(path):
    tables = {}
    cur = None
    want = 0
    with open(path) as f:
        for line in f:
            m = BEGIN_RE.search(line)
            if m:
                typ, name, count = m.group(1), m.group(2), int(m.group(3))
                if name in ("iq2xxs_grid", "ksigns_iq2xs"):
                    cur = (name, count)
                    want = count
                    tables[name] = []
                continue
            if cur and "GGML_TABLE_END" in line:
                if len(tables[cur[0]]) != want:
                    print("error: %s got %d entries, want %d" %
                          (cur[0], len(tables[cur[0]]), want))
                    sys.exit(1)
                cur = None
                continue
            if cur:
                for tok in HEX_RE.findall(line):
                    tables[cur[0]].append(int(tok, 0))
    return tables


def emit_hlsl(tables, path):
    grid = tables["iq2xxs_grid"]
    signs = tables["ksigns_iq2xs"]
    lines = []
    lines.append("/* Generated by vulkan/shaders/gen_iq2_tables.py -- DO NOT EDIT. */")
    lines.append("/* IQ2_XXS lookup tables, extracted from cuda/mmq/ggml-common.h. */")
    lines.append("#ifndef DS4_VULKAN_IQ2_TABLES_HLSL")
    lines.append("#define DS4_VULKAN_IQ2_TABLES_HLSL")
    lines.append("")
    lines.append("/* 256 grid entries, each a uint64 holding 8 int8 values.  Stored")
    lines.append(" * as 512 uint32 (little-endian halves); byte j of entry i is")
    lines.append(" * (iq2xxs_grid_u32[2*i + j/4] >> ((j%%4)*8)) & 0xff. */")
    lines.append("static const uint iq2xxs_grid_u32[512] = {")
    halves = []
    for v in grid:
        halves.append(v & 0xffffffff)
        halves.append((v >> 32) & 0xffffffff)
    for i in range(0, len(halves), 6):
        chunk = ", ".join("0x%08x" % v for v in halves[i:i + 6])
        lines.append("    " + chunk + ",")
    lines.append("};")
    lines.append("")
    lines.append("static const uint iq2xxs_grid_byte(uint idx, uint j) {")
    lines.append("    uint w = iq2xxs_grid_u32[2u * idx + (j >> 2u)];")
    lines.append("    return (w >> ((j & 3u) * 8u)) & 0xffu;")
    lines.append("}")
    lines.append("")
    lines.append("/* 128 sign bitmaps for the 8-value IQ2 groups. */")
    lines.append("static const uint ksigns_iq2xs[128] = {")
    for i in range(0, len(signs), 16):
        chunk = ", ".join("%u" % v for v in signs[i:i + 16])
        lines.append("    " + chunk + ",")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))


def emit_host(tables, path):
    grid = tables["iq2xxs_grid"]
    signs = tables["ksigns_iq2xs"]
    lines = []
    lines.append("/* Generated by vulkan/shaders/gen_iq2_tables.py -- DO NOT EDIT. */")
    lines.append("/* IQ2_XXS lookup tables for the CPU reference. */")
    lines.append("#ifndef DS4_VULKAN_IQ2_TABLES_HOST_H")
    lines.append("#define DS4_VULKAN_IQ2_TABLES_HOST_H")
    lines.append("")
    lines.append("static const uint64_t cpu_iq2xxs_grid[256] = {")
    for i in range(0, len(grid), 4):
        chunk = ", ".join("0x%016xULL" % v for v in grid[i:i + 4])
        lines.append("    " + chunk + ",")
    lines.append("};")
    lines.append("")
    lines.append("static const uint8_t cpu_ksigns_iq2xs[128] = {")
    for i in range(0, len(signs), 16):
        chunk = ", ".join("%u" % v for v in signs[i:i + 16])
        lines.append("    " + chunk + ",")
    lines.append("};")
    lines.append("")
    lines.append("#endif")
    lines.append("")
    with open(path, "w") as f:
        f.write("\n".join(lines))


def main():
    tables = parse_tables(SRC)
    if "iq2xxs_grid" not in tables or "ksigns_iq2xs" not in tables:
        print("error: tables not found in %s" % SRC)
        return 1
    print("iq2xxs_grid = %d, ksigns_iq2xs = %d" %
          (len(tables["iq2xxs_grid"]), len(tables["ksigns_iq2xs"])))
    emit_hlsl(tables, HLSL_OUT)
    emit_host(tables, HOST_OUT)
    print("wrote %s" % HLSL_OUT)
    print("wrote %s" % HOST_OUT)
    return 0


if __name__ == "__main__":
    sys.exit(main())
