#!/usr/bin/env python3
"""Generate the mgpu-probe pure-read/pure-write SPIR-V C headers.

Mirrors vulkan/tools/vkbench/gen_vkbench_shaders.py: compiles each .hlsl with
dxc (HLSL -> SPIR-V) and emits a C header with the byte array.

Usage: python3 gen_spv.py
Requires: dxc on PATH (or DXC env var), python3.
Output:   vulkan/tools/mgpu_probe/{read,write}_spv.h
"""
import os
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))


def find_dxc():
    exe = os.environ.get("DXC", "dxc")
    if shutil.which(exe):
        return exe
    sys.stderr.write("gen_spv.py: dxc not found (set DXC or add it to PATH)\n")
    sys.exit(1)


def compile_spv(dxc, src, entry, out_spv):
    cmd = [dxc, "-T", "cs_6_0", "-E", entry, "-spirv",
           "-fspv-target-env=vulkan1.0",
           "-fvk-t-shift", "0", "0",
           "-fvk-u-shift", "2", "0",
           "-fvk-b-shift", "8", "0",
           "-Fo", out_spv, src]
    subprocess.check_call(cmd)


def emit_header(spv, header, ident):
    data = open(spv, "rb").read()
    with open(header, "w") as f:
        f.write("/* generated by gen_spv.py; do not edit */\n")
        f.write("#include <stdint.h>\n")
        f.write("static const unsigned char %s[] = {\n" % ident)
        for i in range(0, len(data), 12):
            f.write("    " + ", ".join("0x%02x" % b for b in data[i:i + 12]) +
                    ",\n")
        f.write("};\n")
        f.write("static const size_t %s_len = sizeof(%s);\n" % (ident, ident))
    os.unlink(spv)


def main():
    dxc = find_dxc()
    spv = os.path.join(HERE, "spv_tmp.bin")
    compile_spv(dxc, os.path.join(HERE, "read_bench.hlsl"), "main", spv)
    emit_header(spv, os.path.join(HERE, "read_spv.h"), "read_bench_spv")
    compile_spv(dxc, os.path.join(HERE, "write_bench.hlsl"), "main", spv)
    emit_header(spv, os.path.join(HERE, "write_spv.h"), "write_bench_spv")


if __name__ == "__main__":
    main()
